import "./globals.css";
import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
import { UserProvider } from "./context/UserProvider";
import { ProblemProvider } from "./context/ProblemContext";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "PrepMeister",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <UserProvider>
            <ProblemProvider>
            <main className={poppins.className}>{children}</main>
            </ProblemProvider>
          </UserProvider>
        </main>
      </body>
    </html>
  );
}
